name: manual-temp

on: workflow_dispatch

jobs:
  test-actions:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
      
      - name: Install mwmi.govuk.scraper package
        run: |
          install.packages("devtools")
          install.packages("lubridate")
          devtools::install_github("jwallace-co/mwmi.govuk.scraper")
        shell: Rscript {0}
          
      - name: Scrape files
        run: |
          refresh_mwmi=TRUE
          source("R/01_mwmi_scraper.R")